### ISSUE TITLE
H2s on pages not the home page are too big

### ISSUE THREAD

**Issue by aankit** [nycdoe-cs4all/blueprint-learning-site#52]
@ritammehta please adjust the H2s for the pages that are not the home page.

**Comment by iltimasd** [comment]
We committed this

https://github.com/nycdoe-cs4all/blueprint-learning-site/commit/489a0f8c611df0fe677ccb96bc030dbc44be7986

**Comment by aankit** [comment]
check this unit: http://blueprint.cs4all.nyc/activities/23/

Preparation for example is an H2 but its bigger than the H1s.

**Comment by aankit** [comment]
Here is another example of H2's bigger than H1s: http://blueprint.cs4all.nyc/resources/7/

**Comment by ritammehta** [comment]
@iltimasd I just cloned your branch and ran it locally -- it fixes the problem on the unit pages, but not the resource pages -- I think because the units are imported from google docs, and the resource page headers aren't wrapped in any kind of special selector. Also, now the h3 headers are bigger than the h2 ones on the activity pages. 

I think the issue stems from the fact that h2 is used for page headers sitewide, but h1 is used for content in resources. I think we could avoid it altogether by avoiding the use of h2 headers for content on resource pages. Either that or we could wrap the content in resource pages in some kind of selector. Making sitewide headers small is a waste of space and doesn't look any good.
